repos:
  # basic pre-commit hooks
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.253'
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]

  # code formatting with black
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3
        args:
          - --line-length=100

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.26.2
    hooks:
      - id: check-dependabot
        args: [ "--verbose" ]

      - id: check-github-workflows
        args: ["--verbose"]