[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.ruff]
select = ["E", "F", "I", "UP", "B", "ANN", "N", "C4"]
line-length = 100
target-version = "py37"
ignore = ["N806", "ANN101", "ANN102", "N801", "N802", "N803", "ANN401"]
exclude = ["tests"]