name: test

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install pre-commit
        run: |
          pip install pre-commit
      - name: Setup pre-commit hooks
        run: |
          pre-commit install
      - name: Run pre-commit hooks
        run: |
          pre-commit run --all-files

  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # For sonar
      - name: Install dependencies
        run: |
          pip install .
          pip install pytest pytest-cov pandas
      - name: Run tests
        run: |
          pytest --cov=dsp --cov-report xml:coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
