name: build

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pre-commit/action@v3.0.0

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: |
            3.11
            3.10
            3.9
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # For sonar
      - name: Install dependencies
        run: pip install tox
      - name: Run tests
        run: tox

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: build
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: |
          pip install --upgrade build
          python -m build

      - name: publish
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
