name: "ci"

on:
  push:
    branches:
      - main

jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # mosek is not yet ready for '3.11'
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: ['3.9', '3.10', '3.11' ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: cvxgrp/.github/actions/test@main
        with:
          os: ${{ matrix.os }}
          python-version: ${{ matrix.python-version }}
          source-folder: "dsp"
      #- name: Coveralls GitHub Action
      #  uses: coverallsapp/github-action@v2
