name: doc_deploy

on:
    workflow_dispatch:

permissions:
  contents: write


jobs:
  doc_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install and build docs
        run: |
          python -m pip install -e .
          python -m pip install sphinx
          cd docs
          make html

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/_build/html # The folder the action should deploy.
