name: test

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install .
          pip install pytest
      - name: Run tests
        run: |
          pytest
